const fs = require('fs');
const path = require('path');
const file = path.join(__dirname, 'create_verify_slice4.js');
let lines = fs.readFileSync(file, 'utf8').split('\n');

// Find "Test 4: Opening Balances" block and reconstruct everything after it up to END;
const test4Idx = lines.findIndex(l => l.includes("Test 4: Opening Balances"));

if (test4Idx !== -1) {
    // Keep everything up to test 4 setup
    const newLines = lines.slice(0, test4Idx + 1);
    
    // Add the rest correctly
    newLines.push(
`    -- Attempt insert
    BEGIN
        v_ob_id := public.fn_book_opening_balance(prop_a1, owner_a_1, 5000.00, 'debit', CURRENT_DATE);
    EXCEPTION WHEN OTHERS THEN
        RAISE EXCEPTION 'FAIL: Opening balance insert failed: %', SQLERRM;
    END;
    
    -- Duplicate posting
    BEGIN
        PERFORM public.fn_book_opening_balance(prop_a1, owner_a_1, 1000.00, 'debit', CURRENT_DATE);
        RAISE EXCEPTION 'FAIL: Allowed duplicate opening balance';
    EXCEPTION WHEN OTHERS THEN
        IF SQLERRM NOT LIKE '%duplicate key value violates unique constraint%' THEN RAISE EXCEPTION 'FAIL: Expected unique constraint error, got %', SQLERRM; END IF;
    END;
    
    -- Attempt mutation
    BEGIN
        UPDATE public.opening_balances SET amount = 10000 WHERE id = v_ob_id;
        RAISE EXCEPTION 'FAIL: Allowed OB update';
    EXCEPTION WHEN OTHERS THEN
        IF SQLERRM NOT LIKE '%Immutable record%' THEN RAISE EXCEPTION 'FAIL: Expected immutable error, got %', SQLERRM; END IF;
    END;

    -- =========================================================================
    -- TEST 5: NOTIFICATIONS & RLS
    -- =========================================================================
    RAISE NOTICE 'Test 5: Notifications & RLS';
    
    PERFORM set_config('role', 'authenticated', true);
    
    -- Admin A can see the notification generated by verification
    SELECT COUNT(*) INTO v_count FROM public.notifications WHERE society_id = soc_a;
    IF v_count < 1 THEN RAISE EXCEPTION 'FAIL: Notification was not created'; END IF;
    
    PERFORM set_config('request.jwt.claims', '{}'::text, true);
    PERFORM set_config('request.jwt.claims', json_build_object('sub', 'b1000000-0000-0000-0000-000000000010')::text, true);
    SELECT COUNT(*) INTO v_count FROM public.notifications;
    IF v_count != 0 THEN RAISE EXCEPTION 'FAIL: Admin B saw Admin A notifications'; END IF;
    
    PERFORM set_config('request.jwt.claims', '{}'::text, true);
    PERFORM set_config('request.jwt.claims', json_build_object('sub', 'a2000000-0000-0000-0000-000000000021')::text, true);
    SELECT COUNT(*) INTO v_count FROM public.notifications;
    IF v_count < 1 THEN RAISE EXCEPTION 'FAIL: User could not see their own notification'; END IF;

    RAISE NOTICE '--- SLICE 4 TESTS PASSED ---';
END;
$$;
\`;

fs.writeFileSync(path.join(__dirname, '..', 'database', 'verify_slice4.sql'), script);
console.log('verify_slice4.sql generated successfully.');`
    );
    
    fs.writeFileSync(file, newLines.join('\n'));
    console.log('Fixed create_verify_slice4.js');
}
