const fs = require('fs');
const path = require('path');
const file = path.join(__dirname, 'create_verify_slice4.js');
let content = fs.readFileSync(file, 'utf8');

const badBlock = `    -- Attempt mutation
    BEGIN
        UPDATE public.opening_balances SET amount = 10000 WHERE id = v_ob_id;
    PERFORM set_config('request.jwt.claims', json_build_object('sub', 'b1000000-0000-0000-0000-000000000010')::text, true);`;

const replacementBlock = `    -- Attempt mutation
    BEGIN
        UPDATE public.opening_balances SET amount = 10000 WHERE id = v_ob_id;
        RAISE EXCEPTION 'FAIL: Allowed OB update';
    EXCEPTION WHEN OTHERS THEN
        IF SQLERRM NOT LIKE '%Immutable record%' THEN RAISE EXCEPTION 'FAIL: Expected immutable error, got %', SQLERRM; END IF;
    END;

    -- =========================================================================
    -- TEST 5: NOTIFICATIONS & RLS
    -- =========================================================================
    RAISE NOTICE 'Test 5: Notifications & RLS';
    
    PERFORM set_config('role', 'authenticated', true);
    
    -- Admin A can see the notification generated by verification
    SELECT COUNT(*) INTO v_count FROM public.notifications WHERE society_id = soc_a;
    IF v_count < 1 THEN RAISE EXCEPTION 'FAIL: Notification was not created'; END IF;
    
    PERFORM set_config('request.jwt.claims', '{}'::text, true);
    PERFORM set_config('request.jwt.claims', json_build_object('sub', 'b1000000-0000-0000-0000-000000000010')::text, true);`;

content = content.replace(badBlock, replacementBlock);
fs.writeFileSync(file, content);
console.log('Restored Test 5 correctly');
